import {randomUUID} from 'node:crypto'
import {beforeAll,afterAll,expect,it} from 'vitest'
import {actor,admin,cleanup,trip} from './helpers/kinnso-local'
it('an ops alias merge preserves old trip place IDs and resolves published facts',async()=>{
 const owner=await actor(),reviewer=await actor(),outsider=await actor();
 expect((await admin.from('kinnso_ops_members').insert({user_id:reviewer.id,display_name:'Synthetic alias reviewer',status:'active'})).error).toBeNull();
 const rows=await admin.from('places').insert([{name:'Synthetic original place',timezone:'Asia/Tokyo',provider:'manual',status:'active'},{name:'Synthetic canonical place',timezone:'Asia/Tokyo',provider:'manual',status:'active'}]).select('id');expect(rows.error).toBeNull();const [oldId,canonicalId]=rows.data!.map(row=>row.id);
 try {
  expect((await admin.from('kinnso_place_facts').insert({place_id:canonicalId,timezone:'Asia/Tokyo',published:true,verified_at:new Date().toISOString(),source_url:'https://venue.test/hours',opening_hours:[]})).error).toBeNull();
  let t=await trip(owner.client);const day=randomUUID(),stop=randomUUID();t=(await owner.client.rpc('apply_trip_command',{p_trip_id:t.id,p_expected_revision:t.revision,p_request_id:randomUUID(),p_command:{type:'addDay',id:day,offset:0,title:'Day'}})).data;t=(await owner.client.rpc('apply_trip_command',{p_trip_id:t.id,p_expected_revision:t.revision,p_request_id:randomUUID(),p_command:{type:'addStop',id:stop,dayId:day,position:0,input:{title:'Original place',placeId:oldId,travellerNote:'Keep my reference',startMinuteOfDay:600,durationMinutes:30}}})).data;
  const merge={p_alias_id:oldId,p_canonical_id:canonicalId,p_reason:'Synthetic duplicate-place evidence'};
  expect((await outsider.client.rpc('merge_kinnso_place',merge)).error?.message).toContain('forbidden');expect((await reviewer.client.rpc('merge_kinnso_place',merge)).error).toBeNull();expect((await reviewer.client.rpc('merge_kinnso_place',merge)).error).toBeNull();
  const snapshot=await owner.client.rpc('get_trip_snapshot',{p_trip_id:t.id});expect(snapshot.data.days[0].stops[0].placeId).toBe(oldId);expect(snapshot.data.revision).toBe(t.revision);
  const facts=await owner.client.rpc('kinnso_trip_place_facts',{p_trip_id:t.id});expect(facts.error).toBeNull();expect(facts.data[0]).toMatchObject({placeId:oldId,canonicalPlaceId:canonicalId,timezone:'Asia/Tokyo'});
  expect((await admin.from('places').select('status').eq('id',oldId).single()).data?.status).toBe('merged');expect((await outsider.client.from('kinnso_place_aliases').insert({alias_id:canonicalId,canonical_id:oldId,reason:'forged',reviewed_by:outsider.id})).error).not.toBeNull();
 } finally {await admin.from('kinnso_place_aliases').delete().eq('alias_id',oldId);await admin.from('kinnso_place_facts').delete().eq('place_id',canonicalId);await admin.from('places').delete().in('id',[oldId,canonicalId])}
},60000)
let a:Awaited<ReturnType<typeof actor>>,b:Awaited<ReturnType<typeof actor>>,ops:Awaited<ReturnType<typeof actor>>,placeId:string
beforeAll(async()=>{a=await actor();b=await actor();ops=await actor();const p=await admin.from('places').insert({name:'Synthetic place',timezone:'Asia/Tokyo',provider:'manual',status:'active'}).select('id').single();expect(p.error).toBeNull();placeId=p.data!.id;expect((await admin.from('kinnso_ops_members').insert({user_id:ops.id,display_name:'Synthetic reviewer',status:'active'})).error).toBeNull()},60000)
afterAll(async()=>{if(placeId)await admin.from('places').delete().eq('id',placeId);await cleanup()},60000)
it('owner override is revisioned, replay safe and excluded from a shared projection',async()=>{let t=await trip(a.client);const day=randomUUID(),stop=randomUUID();t=(await a.client.rpc('apply_trip_command',{p_trip_id:t.id,p_expected_revision:t.revision,p_request_id:randomUUID(),p_command:{type:'addDay',id:day,offset:0,title:'Day'}})).data;t=(await a.client.rpc('apply_trip_command',{p_trip_id:t.id,p_expected_revision:t.revision,p_request_id:randomUUID(),p_command:{type:'addStop',id:stop,dayId:day,position:0,input:{title:'Place',placeId,travellerNote:'',startMinuteOfDay:600,durationMinutes:30}}})).data;const args={p_trip_id:t.id,p_expected_revision:t.revision,p_request_id:randomUUID(),p_command:{type:'overrideWarning',id:stop,code:'UNVERIFIED_HOURS',reason:'Synthetic personal planning reason'}};expect((await b.client.rpc('apply_trip_command',args)).error?.message).toContain('trip_not_found');const saved=await a.client.rpc('apply_trip_command',args);expect(saved.error).toBeNull();expect(saved.data.revision).toBe(t.revision+1);expect(saved.data.overrides[0].reason).toBe(args.p_command.reason);expect((await a.client.rpc('apply_trip_command',args)).data).toEqual(saved.data);const share=await a.client.rpc('create_trip_share',{p_trip_id:t.id,p_stop_ids:[stop],p_media_ids:[],p_expires_at:new Date(Date.now()+3600000).toISOString()});expect(JSON.stringify(share.data.projection)).not.toContain(args.p_command.reason)})
it('place report is private; active ops review is audited and revoked role loses authority immediately',async()=>{const report=await a.client.rpc('report_kinnso_place',{p_place_id:placeId,p_reason:'Synthetic opening hours correction'});expect(report.error).toBeNull();expect((await b.client.from('kinnso_place_reports').select('id').eq('id',report.data.id)).data).toEqual([]);expect((await b.client.rpc('review_kinnso_place_report',{p_report_id:report.data.id,p_status:'reviewed',p_reason:'Synthetic review evidence'})).error?.message).toContain('forbidden');const queue=await ops.client.rpc('list_kinnso_place_reports');expect(queue.error).toBeNull();expect(queue.data.some((row:{id:string})=>row.id===report.data.id)).toBe(true);expect((await ops.client.rpc('review_kinnso_place_report',{p_report_id:report.data.id,p_status:'resolved',p_reason:'Synthetic review evidence'})).error).toBeNull();expect((await a.client.from('kinnso_place_reports').select('status').eq('id',report.data.id).single()).data?.status).toBe('resolved');expect((await admin.from('kinnso_ops_members').update({status:'paused'}).eq('user_id',ops.id)).error).toBeNull();expect((await ops.client.rpc('list_kinnso_place_reports')).error?.message).toContain('forbidden')})
